# Generated by Django 2.2.5 on 2020-01-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='PlacaDeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Processador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
                ('marca', models.CharField(choices=[('INTEL', 'Intel'), ('AMD', 'Amd'), ('ambos', 'Intel e AMD')], max_length=50, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='MonteSeuPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monteseupc.Processador', verbose_name='Processador')),
            ],
        ),
    ]
