# Generated by Django 2.2.5 on 2020-01-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monteseupc', '0002_auto_20200104_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monteseupc',
            options={'verbose_name': '', 'verbose_name_plural': 's'},
        ),
    ]
